"""Asset provenance database, per brief section 54.

Hollow Crown is intended for commercial release, so for every generated asset
that ships we need to be able to answer, months later and without guessing:
which tool made this, under which plan, from which prompt and which references,
and what was changed by hand afterwards.

Storage is append-only JSONL. That choice is deliberate: it merges cleanly in
git (new lines at the end rather than a rewritten blob), it survives a crashed
batch with the completed records intact, and it stays readable in a diff. The
human-facing table is generated from it on demand rather than edited.
"""

from __future__ import annotations

import hashlib
import json
import os
from dataclasses import asdict, dataclass, field
from datetime import date, datetime, timezone

#: Default database location, relative to the repository root.
DEFAULT_PATH = "Content/Provenance/assets.jsonl"

#: The licence position recorded against generated assets. Keep this accurate:
#: it is the claim we would have to stand behind. Verify the current Meshy
#: terms whenever the plan changes and update the string with the date.
DEFAULT_LICENSE_NOTE = (
    "Meshy paid plan: commercial use of generated assets permitted under the "
    "terms in force on the generation date. Re-verify on plan change."
)


@dataclass
class Record:
    """One production asset and everything we know about its origin."""

    asset_id: str
    file_path: str
    asset_type: str
    generation_tool: str
    generation_date: str
    tool_plan_license: str
    prompt: str
    texture_prompt: str = ""
    source_references: list[str] = field(default_factory=list)
    task_ids: list[str] = field(default_factory=list)
    consumed_credits: int = 0
    triangles: int = 0
    max_texture_edge: int = 0
    sha256: str = ""
    manual_edits: list[str] = field(default_factory=list)
    commercial_rights_notes: str = ""
    validation: str = "unvalidated"
    #: Style reference lineage. Recorded so the art-direction discussion is
    #: auditable without any third-party IP appearing in a prompt.
    style_reference: str = "Hollow Crown house style (see docs/STYLE_GUIDE.md)"

    def to_json(self) -> str:
        return json.dumps(asdict(self), ensure_ascii=False, sort_keys=True)


def sha256_of(path: str) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def today() -> str:
    return date.today().isoformat()


def now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def append(record: Record, path: str = DEFAULT_PATH) -> None:
    """Append one record. Creates the database on first use."""
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "a", encoding="utf-8") as handle:
        handle.write(record.to_json() + "\n")


def load(path: str = DEFAULT_PATH) -> list[Record]:
    """Read every record. Later records win on duplicate asset_id.

    Regenerating an asset appends rather than rewrites, so the file keeps the
    full history while callers see the current state.
    """
    if not os.path.exists(path):
        return []
    latest: dict[str, Record] = {}
    with open(path, encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                payload = json.loads(line)
            except json.JSONDecodeError as exc:
                raise ValueError(f"{path}:{line_number}: malformed record: {exc}") from None
            record = Record(**payload)
            latest[record.asset_id] = record
    return list(latest.values())


def history(asset_id: str, path: str = DEFAULT_PATH) -> list[Record]:
    """Every recorded generation of one asset, oldest first."""
    if not os.path.exists(path):
        return []
    out: list[Record] = []
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            payload = json.loads(line)
            if payload.get("asset_id") == asset_id:
                out.append(Record(**payload))
    return out


def report(path: str = DEFAULT_PATH) -> str:
    """Render the current asset database as a markdown document."""
    records = sorted(load(path), key=lambda r: (r.asset_type, r.asset_id))
    if not records:
        return "# Asset provenance\n\nNo assets recorded yet.\n"

    total_credits = sum(r.consumed_credits for r in records)
    edited = sum(1 for r in records if r.manual_edits)
    lines = [
        "# Asset provenance",
        "",
        f"Generated by `Tools/hollowasset` on {now()}. Do not edit by hand;",
        "regenerate with `python -m hollowasset provenance --report`.",
        "",
        f"- Assets: **{len(records)}**",
        f"- Credits consumed: **{total_credits:,}**",
        f"- Assets with manual edits: **{edited}**",
        "",
        "| Asset | Type | Tool | Date | Tris | Tex | Validation | Manual edits |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for r in records:
        edits = "; ".join(r.manual_edits) if r.manual_edits else "-"
        lines.append(
            f"| `{r.asset_id}` | {r.asset_type} | {r.generation_tool} | {r.generation_date} "
            f"| {r.triangles:,} | {r.max_texture_edge}px | {r.validation} | {edits} |"
        )

    lines += ["", "## Prompts", ""]
    for r in records:
        lines += [
            f"### `{r.asset_id}`",
            "",
            f"- File: `{r.file_path}`",
            f"- Tool: {r.generation_tool}",
            f"- Licence: {r.tool_plan_license}",
            f"- Style reference: {r.style_reference}",
            f"- Meshy task ids: {', '.join(r.task_ids) or '-'}",
            f"- SHA-256: `{r.sha256[:16]}…`" if r.sha256 else "- SHA-256: -",
            "",
            "Geometry prompt:",
            "",
            "```",
            r.prompt,
            "```",
            "",
        ]
        if r.texture_prompt:
            lines += ["Texture prompt:", "", "```", r.texture_prompt, "```", ""]
        if r.source_references:
            lines += ["References: " + ", ".join(f"`{s}`" for s in r.source_references), ""]
        if r.commercial_rights_notes:
            lines += [f"Rights notes: {r.commercial_rights_notes}", ""]
    return "\n".join(lines) + "\n"
